spring.application.name=fp-reporting-service
server.port=9094

spring.datasource.url=jdbc:mysql://localhost:3306/fp_reporting
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=FactoryPulseSecretKeyUsedToHashPasswordsBetterToUseALongHashToEncrypt

fp.identity-base-url=http://localhost:9090
fp.telemetry-base-url=http://localhost:9091
fp.events-base-url=http://localhost:9092
fp.analytics-base-url=http://localhost:9095
