spring.application.name=fp-reporting
server.port=9094

spring.datasource.url=jdbc:mysql://localhost:3306/fp_reporting
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=FactoryPulseSecretKeyUsedToHashPasswordsBetterToUseALongHashToEncrypt

# OEE auto-calculation interval (ms)
oee.auto-calculate-interval-ms=60000

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# Feign + Resilience4j circuit breaker
feign.circuitbreaker.enabled=true

# Default config (fallback for all)
resilience4j.circuitbreaker.instances.default.sliding-window-size=10
resilience4j.circuitbreaker.instances.default.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.default.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.default.record-exceptions=java.lang.Exception

# fp-telemetry circuit breaker
resilience4j.circuitbreaker.instances.fp-telemetry.sliding-window-size=10
resilience4j.circuitbreaker.instances.fp-telemetry.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.fp-telemetry.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.fp-telemetry.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.fp-telemetry.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.fp-telemetry.record-exceptions=java.lang.Exception

# fp-events circuit breaker
resilience4j.circuitbreaker.instances.fp-events.sliding-window-size=10
resilience4j.circuitbreaker.instances.fp-events.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.fp-events.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.fp-events.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.fp-events.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.fp-events.record-exceptions=java.lang.Exception

# fp-identity circuit breaker
resilience4j.circuitbreaker.instances.fp-identity.sliding-window-size=10
resilience4j.circuitbreaker.instances.fp-identity.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.fp-identity.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.fp-identity.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.fp-identity.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.fp-identity.record-exceptions=java.lang.Exception
