spring.application.name=fp-telemetry-service
server.port=9091

spring.datasource.url=jdbc:mysql://localhost:3306/fp_telemetry
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=FactoryPulseSecretKeyUsedToHashPasswordsBetterToUseALongHashToEncrypt

simulator.enabled=true
simulator.telemetry-tick-ms=5000
simulator.production-tick-ms=20000
simulator.good-count-per-tick=20
simulator.reject-rate=0.03

fp.identity-base-url=http://localhost:9090
